Update Actualizar-Arch

diff --git a/Scripts/Actualizar-Arch b/Scripts/Actualizar-Arch
--- a/Scripts/Actualizar-Arch
+++ b/Scripts/Actualizar-Arch
@@ -2,10 +2,17 @@
 echo          ------==Script Creado por GerardoHD==------
 echo       ---=Actualizando Arch Linux=---
 sleep 1s
-echo Si se ejecuta en sesión root, Makepkg no compilará paquetes desde AUR
-echo Comprobando Permisos
-whoami
-echo
+if [ "$(id -u)" -eq 0 ] ; then
+
+	echo "ERROR: No ejecute este Script en una sesiòn Root, porque Makepkg no compilarà paquetes desde AUR"
+
+	echo " Simplemente ejecutelo desde su usuario Regular  "
+
+	echo " Este Script usarà sudo cuando sea necesario. Saliendo."
+
+	exit 1
+
+fi
 #!/bin/bash
 speedtest
 sudo mount -o remount,size=2G,noatime /tmp
