Update Configurar-Arch-KDE

diff --git a/Scripts/Configurar-Arch-KDE b/Scripts/Configurar-Arch-KDE
--- a/Scripts/Configurar-Arch-KDE
+++ b/Scripts/Configurar-Arch-KDE
@@ -4,9 +4,17 @@ echo https://github.com/GerardoHD
 echo Script creado para Arch Linux
 echo Se distribuye con la esperanza de que sea útil, pero sin ninguna garantía al ser un Script Experimental
 sleep 1s
-echo Si se ejecuta en sesión root, Makepkg no compilará paquetes desde AUR
-echo Comprobando Permisos
-whoami
+if [ "$(id -u)" -eq 0 ] ; then
+
+	echo "ERROR: No ejecute este Script en una sesiòn Root, porque Makepkg no compilarà paquetes desde AUR"
+
+	echo " Simplemente ejecutelo desde su usuario Regular  "
+
+	echo " Este Script usarà sudo cuando sea necesario. Saliendo."
+
+	exit 1
+
+fi
 echo Probando conexión a Internet
 ping -c 3 www.archlinux.org
 sudo mount -o remount,size=2G,noatime /tmp
