Update Scripts-master

diff --git a/Scripts/Scripts-master b/Scripts/Scripts-master
--- a/Scripts/Scripts-master
+++ b/Scripts/Scripts-master
@@ -1037,7 +1037,21 @@ sleep 3s
 sudo mv -f /usr/share/gnome-shell/gnome-shell-theme.gresource~ /usr/share/gnome-shell/gnome-shell-theme.gresource
 echo Restart GNOME Shell by pressing Alt+F2, then type r
 
+#Apagar y Actualizar Arch Linux
+if [ "$(id -u)" -eq 0 ] ; then
+ 	echo " ERROR: Makepkg no compilará paquetes desde AUR en una sesión Root "
 
+	echo " Simplemente ejecute este Script desde su usuario Regular. "
+
+	echo " Este Script usará sudo cuando sea necesario. Saliendo."
+
+	exit 1
+
+fi
+#
+yaourt -Syyyuua
+df -h
+sudo poweroff
 
 #Reparar Pacman db.lck
 echo          ------==Script Creado por GerardoHD==------
@@ -1064,6 +1078,21 @@ sleep 1s
 #e2fsck -f -y -v -C 0 /dev/sda7
 #resize2fs -p /dev/sda7
 
+#Reiniciar y Actualizar Arch Linux
+if [ "$(id -u)" -eq 0 ] ; then
+ 	echo " ERROR: Makepkg no compilará paquetes desde AUR en una sesión Root "
+
+	echo " Simplemente ejecute este Script desde su usuario Regular. "
+
+	echo " Este Script usará sudo cuando sea necesario. Saliendo."
+
+	exit 1
+
+fi
+#
+yaourt -Syyyuua
+df -h
+sudo reboot
 
 #Red-Script
 aletorio=`echo $(($RANDOM%6))`
